"""Anchor tests: verify known-correct setsumei paths from real data.

These tests verify specific entries that were manually confirmed as correct.
They serve as regression anchors — if a parse/flatten change breaks these,
the hierarchy assignment is wrong.

Input: long Excel files generated by the pipeline (result/*.xlsx).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from budget_cell.excel_io import read_rows_from_excel_path
from budget_cell.types import FlatRow


ROOT = Path(__file__).resolve().parent.parent
R6_LONG = ROOT / "result" / "r6-long.xlsx"
R8_LONG = ROOT / "result" / "r8-long.xlsx"


def _find_by_setsumei_name(
    rows: tuple[FlatRow, ...],
    name: str,
) -> tuple[FlatRow, ...]:
    return tuple(r for r in rows if r.setsumei_name.strip() == name)


# ---------------------------------------------------------------------------
# R8 anchors
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def r8_rows() -> tuple[FlatRow, ...]:
    pytest.importorskip("openpyxl")
    if not R8_LONG.exists():
        pytest.skip("R8 long Excel not present")
    return read_rows_from_excel_path(str(R8_LONG))


@pytest.fixture(scope="module")
def r6_rows() -> tuple[FlatRow, ...]:
    pytest.importorskip("openpyxl")
    if not R6_LONG.exists():
        pytest.skip("R6 long Excel not present")
    return read_rows_from_excel_path(str(R6_LONG))


class TestR8ShoubouShirei:
    """R8 消防指令センター: L1(code=006) → L2(code=001) cross-code hierarchy."""

    def test_l1_path(self, r8_rows: tuple[FlatRow, ...]) -> None:
        hits = _find_by_setsumei_name(r8_rows, "富士市・富士宮市消防指令センター費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path == ("富士市・富士宮市消防指令センター費",)
        assert hits[0].setsumei_level == 1
        assert hits[0].setsumei_code == "006"

    def test_l2_path(self, r8_rows: tuple[FlatRow, ...]) -> None:
        hits = _find_by_setsumei_name(r8_rows, "富士市・富士宮市消防指令センター運営事業費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path == (
            "富士市・富士宮市消防指令センター費",
            "富士市・富士宮市消防指令センター運営事業費",
        )
        assert hits[0].setsumei_level == 2
        # Key regression: code differs from L1
        assert hits[0].setsumei_code == "001"

    def test_l2_parent_is_not_kyuukyuu(self, r8_rows: tuple[FlatRow, ...]) -> None:
        """The original bug: L2 was assigned L1='救急活動費' instead of 消防指令センター費."""
        hits = _find_by_setsumei_name(r8_rows, "富士市・富士宮市消防指令センター運営事業費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path[0] != "救急活動費"


class TestR6ShoubouShirei:
    """R6 消防指令センター: same cross-code hierarchy pattern."""

    def test_l1_path(self, r6_rows: tuple[FlatRow, ...]) -> None:
        hits = _find_by_setsumei_name(r6_rows, "富士市・富士宮市消防指令センター費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path == ("富士市・富士宮市消防指令センター費",)

    def test_l2_path(self, r6_rows: tuple[FlatRow, ...]) -> None:
        hits = _find_by_setsumei_name(r6_rows, "富士市・富士宮市消防指令センター運営事業費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path == (
            "富士市・富士宮市消防指令センター費",
            "富士市・富士宮市消防指令センター運営事業費",
        )

    def test_l2_parent_is_not_yobou(self, r6_rows: tuple[FlatRow, ...]) -> None:
        """The original bug: L2 was assigned L1='予防広報事業費' instead of 消防指令センター費."""
        hits = _find_by_setsumei_name(r6_rows, "富士市・富士宮市消防指令センター運営事業費")
        assert len(hits) >= 1
        assert hits[0].setsumei_path[0] != "予防広報事業費"


class TestR8BasicHierarchy:
    """R8 basic L1→L2 hierarchy (議会費 給与費) — smoke test."""

    def test_l1_gives_single_element_path(self, r8_rows: tuple[FlatRow, ...]) -> None:
        hits = _find_by_setsumei_name(r8_rows, "給与費")
        # 給与費 appears in multiple moku — just check the first one has a path
        assert len(hits) >= 1
        assert hits[0].setsumei_path == ("給与費",)
        assert hits[0].setsumei_level == 1
